spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./target/h2db/db/taco-cloud;DB_CLOSE_DELAY=-1
    username: sa
    password:
    initialization-mode: always
  h2:
    console:
      enabled: true
  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: create-drop