version: '3'

services:
  worldgdp-mysql-compose:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "pwd"
    ports:
      - "33306:3306"
    volumes:
      - .docker/worldgdp/mysql/data:/var/lib/mysql
      - .docker/worldgdp/mysql/com.github.hsseo0501.worldgdp.test.config:/etc/mysql/conf.d
    networks:
      - worldgdp-mysql-compose-network

networks:
  worldgdp-mysql-compose-network:
    driver: bridge